language: node_js
node_js:
  - "v10.15.0"
cache:
  directories:
    - "node_modules"
script:
  - echo "Deploy don pale project"
install:
  - npm install
  - npm i -g firebase-tools
  - npm run generate
after_success:
  - firebase deploy --only hosting:donpale --token "$FIREBASE_TOKEN"
